import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  compileCanonicalEntities,
  validateCanonicalEntity,
  type CanonicalEntity,
  type CanonicalSpell,
  type JudgementCall,
} from "../library/src/canon/index.ts";

interface ParsedCanonFile {
  path: string;
  frontmatter: Record<string, unknown>;
  bodyMd: string;
}

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const canonDir = path.join(rootDir, "content", "canon");
const generatedFile = path.join(rootDir, "library", "src", "generated", "index.ts");

function isObject(value: unknown): value is Record<string, unknown> {
  return Boolean(value) && typeof value === "object" && !Array.isArray(value);
}

async function walk(dir: string): Promise<string[]> {
  const entries = await fs.readdir(dir, { withFileTypes: true });
  const files = await Promise.all(
    entries.map(async (entry) => {
      const fullPath = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        return walk(fullPath);
      }
      if (entry.isFile() && fullPath.endsWith(".md")) {
        return [fullPath];
      }
      return [];
    }),
  );

  return files.flat().sort();
}

function parseCanonicalMarkdown(filePath: string, markdown: string): ParsedCanonFile {
  const match = markdown.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);
  if (!match) {
    throw new Error(`${filePath}: expected JSON frontmatter wrapped in --- blocks`);
  }

  const [, frontmatterBlock, bodyMd] = match;
  let frontmatter: unknown;
  try {
    frontmatter = JSON.parse(frontmatterBlock);
  } catch (error) {
    throw new Error(
      `${filePath}: invalid JSON frontmatter: ${error instanceof Error ? error.message : String(error)}`,
    );
  }

  if (!isObject(frontmatter)) {
    throw new Error(`${filePath}: frontmatter must decode to an object`);
  }

  return {
    path: filePath,
    frontmatter,
    bodyMd: bodyMd.trim(),
  };
}

function assertUnique(entities: CanonicalEntity[]): void {
  const ids = new Map<string, string>();
  const slugs = new Map<string, string>();

  for (const entity of entities) {
    const existingId = ids.get(entity.id);
    if (existingId) {
      throw new Error(`duplicate entity id "${entity.id}" found in ${existingId} and ${entity.name}`);
    }
    ids.set(entity.id, entity.name);

    const existingSlug = slugs.get(entity.slug);
    if (existingSlug) {
      throw new Error(
        `duplicate entity slug "${entity.slug}" found in ${existingSlug} and ${entity.name}`,
      );
    }
    slugs.set(entity.slug, entity.name);
  }
}

function assertDerivedReferencesResolve(entities: CanonicalEntity[]): void {
  const entityKeys = new Set(entities.map((entity) => `${entity.packId}:${entity.id}`));

  for (const entity of entities) {
    const judgement = entity.judgement as JudgementCall | null;
    if (!judgement) {
      continue;
    }

    for (const source of judgement.derivedFrom) {
      if (!source.packId || !source.entityId) {
        continue;
      }

      const key = `${source.packId}:${source.entityId}`;
      if (!entityKeys.has(key)) {
        throw new Error(
          `${entity.id}: unresolved derivedFrom reference ${key} (${source.label})`,
        );
      }
    }
  }
}

function assertCanonicalReferencesResolve(entities: CanonicalEntity[]): void {
  const entityKeys = new Set(entities.map((entity) => `${entity.packId}:${entity.id}`));

  for (const entity of entities) {
    if (entity.type !== "spell") {
      continue;
    }

    const spell = entity as CanonicalSpell;
    if (spell.overlayTarget) {
      const overlayKey = `${spell.overlayTarget.packId}:${spell.overlayTarget.entityId}`;
      if (!entityKeys.has(overlayKey)) {
        throw new Error(`${spell.id}: unresolved overlayTarget reference ${overlayKey}`);
      }
    }

    for (const abilityId of spell.linkedAaAbilityIds ?? []) {
      const abilityKey = `advanced-adventurers:${abilityId}`;
      if (!entityKeys.has(abilityKey)) {
        throw new Error(`${spell.id}: unresolved linkedAaAbilityId ${abilityId}`);
      }
    }
  }
}

function toConstExport<T>(name: string, value: T, typeName: string): string {
  return `export const ${name} = ${JSON.stringify(value, null, 2)} satisfies ${typeName};`;
}

async function writeGeneratedFile(entities: CanonicalEntity[]): Promise<void> {
  const compiled = compileCanonicalEntities(entities);

  const fileContents = `// This file is generated by scripts/compile-canon.ts.
import type {
  CanonicalAAAbility,
  CanonicalClass,
  CanonicalClassFeature,
  CanonicalCondition,
  CanonicalContentManifest,
  CanonicalEntity,
  CanonicalEquipment,
  CanonicalFeat,
  CanonicalRule,
  CanonicalSpecies,
  CanonicalSpell,
} from "../canon/types.ts";
import type { Spell } from "../types/spell.ts";

${toConstExport("generatedContentManifest", compiled.manifest, "CanonicalContentManifest")}

${toConstExport("allCanonEntities", compiled.entities, "CanonicalEntity[]")}

${toConstExport("allCanonSpells", compiled.spells, "CanonicalSpell[]")}

${toConstExport("allCanonRules", compiled.rules, "CanonicalRule[]")}

${toConstExport("allCanonConditions", compiled.conditions, "CanonicalCondition[]")}

${toConstExport("allCanonEquipment", compiled.equipment, "CanonicalEquipment[]")}

${toConstExport("allCanonFeats", compiled.feats, "CanonicalFeat[]")}

${toConstExport("allCanonSpecies", compiled.species, "CanonicalSpecies[]")}

${toConstExport("allCanonClasses", compiled.classes, "CanonicalClass[]")}

${toConstExport("allCanonClassFeatures", compiled.classFeatures, "CanonicalClassFeature[]")}

${toConstExport("allCanonAaAbilities", compiled.aaAbilities, "CanonicalAAAbility[]")}

${toConstExport("allRuntimeSpells", compiled.runtimeSpells, "Spell[]")}
`;

  await fs.mkdir(path.dirname(generatedFile), { recursive: true });
  await fs.writeFile(generatedFile, fileContents);
}

async function main(): Promise<void> {
  const files = await walk(canonDir);
  const parsed = await Promise.all(
    files.map(async (filePath) =>
      parseCanonicalMarkdown(filePath, await fs.readFile(filePath, "utf8"))
    ),
  );

  const entities = parsed.map((file) =>
    validateCanonicalEntity(file.frontmatter, file.bodyMd, file.path)
  );

  assertUnique(entities);
  assertDerivedReferencesResolve(entities);
  assertCanonicalReferencesResolve(entities);
  await writeGeneratedFile(entities);

  console.log(`compiled ${entities.length} canonical entities`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
